// <auto-generated />
using System;
using GestorTeocratico.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GestorTeocratico.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250725182458_AddEntities")]
    partial class AddEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GestorTeocratico.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("GestorTeocratico.Entities.Congregation", b =>
                {
                    b.Property<Guid>("CongregationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("City")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("MidweekMeetingDayEvenYear")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MidweekMeetingDayOddYear")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("WeekendMeetingDayEvenYear")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WeekendMeetingDayOddYear")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CongregationId");

                    b.ToTable("Congregations");
                });

            modelBuilder.Entity("GestorTeocratico.Entities.Department", b =>
                {
                    b.Property<Guid>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CongregationId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<Guid?>("ResponsiblePublisherId")
                        .HasColumnType("uuid");

                    b.HasKey("DepartmentId");

                    b.HasIndex("CongregationId");

                    b.HasIndex("ResponsiblePublisherId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("GestorTeocratico.Entities.MeetingSchedule", b =>
                {
                    b.Property<Guid>("MeetingScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CongregationId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("MeetingTypeId")
                        .HasColumnType("uuid");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<int>("WeekOfYear")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("MeetingScheduleId");

                    b.HasIndex("CongregationId");

                    b.HasIndex("MeetingTypeId");

                    b.ToTable("MeetingSchedules");
                });

            modelBuilder.Entity("GestorTeocratico.Entities.MeetingType", b =>
                {
                    b.Property<Guid>("MeetingTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<Guid>("TypeMeetingTypeId")
                        .HasColumnType("uuid");

                    b.HasKey("MeetingTypeId");

                    b.HasIndex("TypeMeetingTypeId");

                    b.ToTable("MeetingTypes");
                });

            modelBuilder.Entity("GestorTeocratico.Entities.Publisher", b =>
                {
                    b.Property<Guid>("PublisherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CongregationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("MotherLastName")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<int>("Privilege")
                        .HasColumnType("integer");

                    b.HasKey("PublisherId");

                    b.HasIndex("CongregationId");

                    b.ToTable("Publishers");
                });

            modelBuilder.Entity("GestorTeocratico.Entities.PublisherResponsibility", b =>
                {
                    b.Property<Guid>("PublisherId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ResponsibilityId")
                        .HasColumnType("uuid");

                    b.HasKey("PublisherId", "ResponsibilityId");

                    b.HasIndex("ResponsibilityId");

                    b.ToTable("PublisherResponsibilities");
                });

            modelBuilder.Entity("GestorTeocratico.Entities.Responsibility", b =>
                {
                    b.Property<Guid>("ResponsibilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ResponsibilityId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Responsibilities");
                });

            modelBuilder.Entity("GestorTeocratico.Entities.ResponsibilityAssignment", b =>
                {
                    b.Property<Guid>("MeetingScheduleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ResponsibilityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PublisherId")
                        .HasColumnType("uuid");

                    b.HasKey("MeetingScheduleId", "ResponsibilityId", "PublisherId");

                    b.HasIndex("PublisherId");

                    b.HasIndex("ResponsibilityId");

                    b.ToTable("ResponsibilityAssignments");
                });

            modelBuilder.Entity("GestorTeocratico.Entities.ResponsibilityAssignmentConfig", b =>
                {
                    b.Property<Guid>("ResponsibilityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MeetingTypeId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("ResponsibilityId", "MeetingTypeId");

                    b.HasIndex("MeetingTypeId");

                    b.ToTable("ResponsibilityAssignmentConfigs");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GestorTeocratico.Entities.Department", b =>
                {
                    b.HasOne("GestorTeocratico.Entities.Congregation", "Congregation")
                        .WithMany("Departments")
                        .HasForeignKey("CongregationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestorTeocratico.Entities.Publisher", "ResponsiblePublisher")
                        .WithMany("ResponsibleDepartments")
                        .HasForeignKey("ResponsiblePublisherId");

                    b.Navigation("Congregation");

                    b.Navigation("ResponsiblePublisher");
                });

            modelBuilder.Entity("GestorTeocratico.Entities.MeetingSchedule", b =>
                {
                    b.HasOne("GestorTeocratico.Entities.Congregation", "Congregation")
                        .WithMany("MeetingSchedules")
                        .HasForeignKey("CongregationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestorTeocratico.Entities.MeetingType", "MeetingType")
                        .WithMany()
                        .HasForeignKey("MeetingTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Congregation");

                    b.Navigation("MeetingType");
                });

            modelBuilder.Entity("GestorTeocratico.Entities.MeetingType", b =>
                {
                    b.HasOne("GestorTeocratico.Entities.MeetingType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeMeetingTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("GestorTeocratico.Entities.Publisher", b =>
                {
                    b.HasOne("GestorTeocratico.Entities.Congregation", "Congregation")
                        .WithMany("Publishers")
                        .HasForeignKey("CongregationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Congregation");
                });

            modelBuilder.Entity("GestorTeocratico.Entities.PublisherResponsibility", b =>
                {
                    b.HasOne("GestorTeocratico.Entities.Publisher", "Publisher")
                        .WithMany("PublisherResponsibilities")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestorTeocratico.Entities.Responsibility", "Responsibility")
                        .WithMany("PublisherResponsibilities")
                        .HasForeignKey("ResponsibilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Publisher");

                    b.Navigation("Responsibility");
                });

            modelBuilder.Entity("GestorTeocratico.Entities.Responsibility", b =>
                {
                    b.HasOne("GestorTeocratico.Entities.Department", "Department")
                        .WithMany("Responsibilities")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("GestorTeocratico.Entities.ResponsibilityAssignment", b =>
                {
                    b.HasOne("GestorTeocratico.Entities.MeetingSchedule", "MeetingSchedule")
                        .WithMany("ResponsibilityAssignments")
                        .HasForeignKey("MeetingScheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestorTeocratico.Entities.Publisher", "Publisher")
                        .WithMany()
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestorTeocratico.Entities.Responsibility", "Responsibility")
                        .WithMany()
                        .HasForeignKey("ResponsibilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MeetingSchedule");

                    b.Navigation("Publisher");

                    b.Navigation("Responsibility");
                });

            modelBuilder.Entity("GestorTeocratico.Entities.ResponsibilityAssignmentConfig", b =>
                {
                    b.HasOne("GestorTeocratico.Entities.MeetingType", "MeetingType")
                        .WithMany()
                        .HasForeignKey("MeetingTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestorTeocratico.Entities.Responsibility", "Responsibility")
                        .WithMany()
                        .HasForeignKey("ResponsibilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MeetingType");

                    b.Navigation("Responsibility");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("GestorTeocratico.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("GestorTeocratico.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestorTeocratico.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("GestorTeocratico.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GestorTeocratico.Entities.Congregation", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("MeetingSchedules");

                    b.Navigation("Publishers");
                });

            modelBuilder.Entity("GestorTeocratico.Entities.Department", b =>
                {
                    b.Navigation("Responsibilities");
                });

            modelBuilder.Entity("GestorTeocratico.Entities.MeetingSchedule", b =>
                {
                    b.Navigation("ResponsibilityAssignments");
                });

            modelBuilder.Entity("GestorTeocratico.Entities.Publisher", b =>
                {
                    b.Navigation("PublisherResponsibilities");

                    b.Navigation("ResponsibleDepartments");
                });

            modelBuilder.Entity("GestorTeocratico.Entities.Responsibility", b =>
                {
                    b.Navigation("PublisherResponsibilities");
                });
#pragma warning restore 612, 618
        }
    }
}
